status = [
    "Check clippy (ubuntu-latest)",
    "Check rustfmt (ubuntu-latest)",
    "Unit Test Linux (ubuntu-latest)",
    "Doc Test (ubuntu-latest)",
]
delete_merged_branches = true
timeout_sec = 1200 # 20 mins
