status = [
    "Rustfmt (ubuntu-latest)",
    "Clippy (ubuntu-latest)",
    "Doc tests (ubuntu-latest)",
    "Unit tests (ubuntu-latest)",
    "Unit tests (macos-latest)",
]
use_squash_merge = true
delete_merged_branches = true
timeout_sec = 1800 # 30 mins
